title: Willy's willy
email: starwars78910@gmail.com
description: A Blog by a CSIE student
author: Willy Huang
baseurl: "/willyswilly"
url: "https://willymaster7749.github.io"

# Social Profiles
twitter_username:
github_username: willymaster7749
facebook_username: 黃定鈞
instagram_username: willy7749
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics: UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/posts/page:num/"
plugins:
    - jekyll-feed
    - jekyll-paginate
    - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
